"use client";

import { AlertTriangle, CheckCircle2, Clock3, Flag, Globe2, Mail, ShieldCheck, TrendingUp, Users } from "lucide-react";

export function PaymentControlAnalyticsPanel() {
  return <section className="px-5 pb-10 md:px-8" aria-labelledby="payment-control-report-title"><div className="rounded-lg border border-border bg-[var(--primary-strong)] p-6 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-[11px] font-semibold text-[#f2a043]">Phase 3 · manual control</div><h2 id="payment-control-report-title" className="mt-2 text-[28px] font-semibold tracking-[-.02em]">Deposit and verification health</h2><p className="mt-2 max-w-2xl text-[14px] leading-6 text-white/65">Verified money only. Submitted claims, proof exceptions, refunds, and ready-to-confirm reservations stay separate.</p></div><span className="rounded-full bg-card/10 px-3 py-1.5 text-[10px] font-semibold text-white/70">Operational · not financial statements</span></div><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-6"><DarkMetric label="Required" value="₱18k" /><DarkMetric label="Verified net" value="₱2.5k" /><DarkMetric label="Unverified" value="₱13k" /><DarkMetric label="Refunded" value="₱0" /><DarkMetric label="Median review" value="22m" /><DarkMetric label="Open exceptions" value="2" /></div><div className="mt-5 grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-3"><div className="text-[12px] text-white/65"><b className="block text-white">0 emergency self-checks</b>Target remains zero.</div><div className="text-[12px] text-white/65"><b className="block text-white">1 proof rejection</b>Correction still preserves history.</div><div className="text-[12px] text-white/65"><b className="block text-white">0 auto-confirmations</b>Confirmation always stays manual.</div></div></div></section>;
}

function DarkMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-card/[.07] p-4"><div className="text-[10px] text-white/55">{label}</div><div className="mt-1 text-[21px] font-semibold tracking-[-.015em]">{value}</div></div>; }

export function PublicRequestAnalyticsPanel() {
  const funnel = [
    { label: "Submitted", value: 42, width: "100%", color: "#e98917" },
    { label: "Reviewed", value: 35, width: "83%", color: "#3f7b6d" },
    { label: "Converted", value: 24, width: "57%", color: "#185142" },
    { label: "Declined / withdrawn", value: 8, width: "19%", color: "#9ea9a5" },
  ];
  return <section className="px-5 pb-10 md:px-8" aria-labelledby="public-request-report-title"><div className="rounded-lg border border-[var(--border)] bg-card p-6 shadow-soft"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--accent-strong)]">Phase 2 · requests are not revenue</div><h2 id="public-request-report-title" className="mt-2 font-display text-2xl text-[var(--foreground)]">Public request operations</h2><p className="mt-1 text-xs text-[var(--muted-foreground)]">Intake volume, response performance, and request-to-reservation conversion.</p></div><span className="rounded-full bg-[#f2f4ef] px-3 py-1.5 text-[10px] font-bold text-[#62716d]">Preview dataset · last 30 days</span></div><div className="mt-6 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-3">{funnel.map((item) => <div key={item.label} className="grid grid-cols-[120px_1fr_30px] items-center gap-3 text-xs"><span className="font-semibold text-[#52625e]">{item.label}</span><div className="h-8 overflow-hidden rounded-lg bg-[#f0f2ee]"><div className="flex h-full items-center rounded-lg px-3 text-[10px] font-bold text-white" style={{ width: item.width, background: item.color }}>{Math.round(item.value / 42 * 100)}%</div></div><b className="text-right text-[#2d423e]">{item.value}</b></div>)}</div><div className="grid grid-cols-2 gap-3"><AnalyticsMetric icon={<Clock3 size={16} />} label="Median first review" value="38m" /><AnalyticsMetric icon={<TrendingUp size={16} />} label="Conversion rate" value="57%" /><AnalyticsMetric icon={<Users size={16} />} label="Change requests" value="6" /><AnalyticsMetric icon={<Mail size={16} />} label="Email failures" value="0" /></div></div><p className="mt-5 border-t border-[var(--border)] pt-4 text-[10px] leading-5 text-[#85908d]">Submitted requests and requested covers remain separate from confirmed reservation and revenue reporting. Campaign attribution is included only when consent-compatible.</p></div></section>;
}

function AnalyticsMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return <div className="rounded-lg border border-[var(--border)] bg-[var(--background)] p-4"><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.08em] text-[var(--muted-foreground)]">{icon}{label}</div><div className="mt-2 font-display text-2xl font-bold text-[#29413d]">{value}</div></div>;
}

export function Phase2PolicyPanel({ notify }: { notify: (message: string) => void }) {
  return <section className="px-5 pb-10 md:px-8"><div className="rounded-lg border border-[var(--border)] bg-card p-5 shadow-soft"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><span className="rounded-lg bg-[#edf1eb] p-2.5 text-[#365b54]"><Globe2 size={19} /></span><div><h2 className="font-display text-xl text-[var(--foreground)]">Public booking request policy</h2><p className="mt-1 text-xs leading-5 text-[#788481]">Production intake remains disabled until every placeholder is approved.</p></div></div><div className="flex items-center gap-2 rounded-full border border-rose-200 bg-rose-50 px-3 py-2 text-[10px] font-bold uppercase tracking-[.08em] text-rose-700"><Flag size={13} />Production disabled</div></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><PolicyValue label="Lead time" value="2 hours" /><PolicyValue label="Advance window" value="90 days" /><PolicyValue label="Slot interval" value="30 min" /><PolicyValue label="Response target" value="60 min" /></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-2 text-xs font-bold text-amber-900"><AlertTriangle size={15} />Management decisions still required</div><p className="mt-2 text-[11px] leading-5 text-amber-800">Terms, special dates, party limits, retention, sender identity, CAPTCHA, response owner, and soft-launch request types.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><FeatureGate icon={<ShieldCheck size={15} />} label="Environment flag" value="Preview on" on /><FeatureGate icon={<Globe2 size={15} />} label="Outlet intake" value="Off" /><FeatureGate icon={<Users size={15} />} label="Request types" value="Preview all" on /><FeatureGate icon={<Mail size={15} />} label="External email" value="Off · local sink" /></div><div className="mt-5 flex flex-col gap-3 border-t border-[var(--border)] pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-[10px] leading-5 text-[var(--muted-foreground)]">Disabling intake preserves staff access, guest manage links, and all submitted data.</p><button onClick={() => notify("Phase 2 preview policy saved. Production intake remains disabled.")} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[var(--primary-strong)] px-4 text-xs font-bold text-white"><CheckCircle2 size={15} />Save preview policy</button></div></div></section>;
}

function PolicyValue({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-[var(--border)] bg-[var(--background)] p-3"><div className="text-[9px] font-bold uppercase tracking-[.08em] text-[var(--muted-foreground)]">{label}</div><div className="mt-1.5 text-sm font-bold text-[var(--secondary-foreground)]">{value}</div><div className="mt-1 text-[9px] text-amber-700">Placeholder</div></div>; }
function FeatureGate({ icon, label, value, on }: { icon: React.ReactNode; label: string; value: string; on?: boolean }) { return <div className="flex items-center gap-3 rounded-lg border border-[var(--border)] p-3"><span className={`rounded-lg p-2 ${on ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{icon}</span><div><div className="text-[9px] font-bold uppercase tracking-[.07em] text-[var(--muted-foreground)]">{label}</div><div className="mt-0.5 text-xs font-bold text-[var(--secondary-foreground)]">{value}</div></div></div>; }
